"""Render a compact Stage 4 report from generated regime evidence."""
from __future__ import annotations

import argparse
import json
from pathlib import Path

import pandas as pd


ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "results" / "regime"
REPORT = ROOT / "REGIME_DATA_REPORT.md"
SANITY_WINDOWS = (
    ("2020-03-01", "2020-05-31", "2020 market shock"),
    ("2021-01-01", "2021-04-30", "2021 rising market"),
    ("2022-04-01", "2022-07-31", "2022 falling market"),
)


def _table(frame: pd.DataFrame) -> str:
    return frame.to_markdown(index=False)


def render(outdir: Path = OUT) -> str:
    daily = pd.read_csv(outdir / "regime_daily.csv", parse_dates=["date"])
    episodes = pd.read_csv(outdir / "regime_episodes.csv")
    btc_episodes = pd.read_csv(outdir / "regime_btc_episodes.csv")
    transitions = pd.read_csv(outdir / "regime_transitions.csv")
    manifest = json.loads((outdir / "regime_manifest.json").read_text(encoding="utf-8"))
    btc = daily[daily["pair"] == "BTC/USDT"].copy()
    btc_counts = (btc.groupby("btc_regime").size().rename("days").reset_index()
                  .rename(columns={"btc_regime": "state"}))
    coin_counts = (daily.groupby("coin_regime").size().rename("days").reset_index()
                   .rename(columns={"coin_regime": "state"}))
    episode_summary = (episodes.groupby("regime").agg(
        episodes=("episode_id", "size"), days=("days", "sum"),
        median_days=("days", "median"), max_days=("days", "max")).reset_index())
    lines = [
        "# Regime data validation — Stages 3 and 4", "",
        "Generated by `python -m regime.regime_engine` and checked by",
        "`python -m regime.validate_regime`. The authoritative parameter and",
        "input/output fingerprints are in `results/regime/regime_manifest.json`.", "",
        "Runtime: " + ", ".join(f"{name} {version}" for name, version in
                                 manifest["runtime_versions"].items()) + ".", "",
        f"The causal daily table contains **{len(daily)}** pair-days across",
        f"**{daily['pair'].nunique()}** audit pairs. Every feature is lagged by one",
        "completed UTC daily candle before it becomes available.", "",
        "## State coverage", "", "BTC/global state:", "", _table(btc_counts), "",
        "Local coin states across available pair-days:", "", _table(coin_counts), "",
        "## Episodes", "", _table(episode_summary), "",
        f"The global BTC sequence contains **{len(btc_episodes)}** contiguous episodes",
        f"covering **{int(btc_episodes['days'].sum())}** unique UTC days.", "",
        f"The transition table contains **{len(transitions)}** pair/state edges.", "",
        "## Fixed sanity timelines", "",
        "The following weekly samples are visual sanity checks selected before",
        "strategy outcomes are inspected. They do not set or tune thresholds.", "",
    ]
    columns = ["date", "btc_regime", "btc_adx", "btc_plus_di", "btc_minus_di",
               "btc_return_90d", "btc_ser_30"]
    for start, end, label in SANITY_WINDOWS:
        sample = btc[(btc["date"] >= start) & (btc["date"] <= end)][columns].iloc[::7].copy()
        sample["date"] = sample["date"].dt.strftime("%Y-%m-%d")
        for col in columns[2:]:
            sample[col] = sample[col].round(3)
        lines.extend([f"### {label}", "", _table(sample), ""])
    lines.extend([
        "## Structural checks", "",
        "- unique `(pair, date)` keys;",
        "- identical BTC features across all pair rows on a date;",
        "- state values restricted to the frozen vocabulary;",
        "- episode durations partition every daily row;",
        "- generated output hashes match the manifest;",
        "- synthetic trend/range, one-day lag, and future-mutation tests pass.", "",
    ])
    return "\n".join(lines)


def main(argv=None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--outdir", type=Path, default=OUT)
    parser.add_argument("--report", type=Path, default=REPORT)
    args = parser.parse_args(argv)
    args.report.write_text(render(args.outdir), encoding="utf-8")
    print(f"wrote {args.report}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
