# -*- coding: utf-8 -*-
"""resolvable — can your history answer the question you are asking of it?

A barrier claim ("price hits +X before -X more often than chance") is settled
by races, not by candles. A race starts somewhere and ends when one of the two
barriers is touched. The next independent race starts where the last one
finished. Everything in between is the same race, counted twice.

Most barrier backtests report the number of candles. That number is large and
irrelevant. The number that decides whether your result can exist is how many
non-overlapping races fit in the history you have — and for wide barriers that
number is astonishingly small.

This script prints both, next to the sample size you would actually need.

    python resolvable.py --fetch    download and count, writes resolvable_run.json
    python resolvable.py            render resolvable_run.json into RESOLVABLE.md

Nothing here is a strategy. It is the question you ask before running one.
"""
from __future__ import print_function

import datetime as dt
import io
import json
import math
import os
import sys
import time

BASE = "https://fapi.binance.com"
HERE = os.path.dirname(os.path.abspath(__file__))
RUN = os.path.join(HERE, "resolvable_run.json")
DOC = os.path.join(HERE, "RESOLVABLE.md")

SYMBOLS = ["BTCUSDT", "ETHUSDT"]
BARRIERS_BPS = [500, 1000, 2000, 3000, 5000]
START = "2019-09-01"
# alternatives the power table is computed against; declared, not searched
ALTERNATIVES = [0.53, 0.55, 0.60, 0.65]


def _klines(symbol, start):
    import urllib.request
    out = []
    t = int(dt.datetime.strptime(start, "%Y-%m-%d")
            .replace(tzinfo=dt.timezone.utc).timestamp() * 1000)
    # TOTAL: the fetch runs up to now on purpose; resolvable_run.json pins what
    # was downloaded, and the rendered table comes from that file, not the net.
    now = int(time.time() * 1000)
    while t < now:
        url = ("%s/fapi/v1/klines?symbol=%s&interval=1d&startTime=%d&limit=1500"
               % (BASE, symbol, t))
        chunk = json.load(urllib.request.urlopen(url, timeout=45))
        if not chunk:
            break
        out += [(int(x[0]), float(x[2]), float(x[3]), float(x[4])) for x in chunk]
        t = int(chunk[-1][0]) + 1
        if len(chunk) < 1500:
            break
    return out


def races(candles, bps):
    """Non-overlapping races. A race ends on first touch; the next one starts
    there. Overlapping races are the same market event counted twice."""
    high = [c[1] for c in candles]
    low = [c[2] for c in candles]
    close = [c[3] for c in candles]
    n, i, out = len(close), 0, []
    while i < n - 1:
        p = close[i]
        up, dn = p * (1 + bps / 10000.0), p * (1 - bps / 10000.0)
        j = i + 1
        while j < n:
            if high[j] >= up:
                out.append((i, j, 1))
                break
            if low[j] <= dn:
                out.append((i, j, -1))
                break
            j += 1
        if j >= n:
            break
        i = j
    return out


def needed(p_alt, power=0.80, alpha=0.05):
    """Two-sided test of p_alt against 0.50, normal approximation."""
    z_a, z_b = 1.959964, 0.841621
    num = z_a * math.sqrt(0.25) + z_b * math.sqrt(p_alt * (1 - p_alt))
    return int(math.ceil((num / (p_alt - 0.5)) ** 2))


def compute():
    out = {"start": START, "alternatives": ALTERNATIVES,
           "needed": {("%.2f" % a): needed(a) for a in ALTERNATIVES},
           "symbols": {}}
    for sym in SYMBOLS:
        candles = _klines(sym, START)
        span_years = (candles[-1][0] - candles[0][0]) / 1000.0 / 86400 / 365.25
        rec = {"candles": len(candles), "years": span_years, "barriers": []}
        for b in BARRIERS_BPS:
            r = races(candles, b)
            if not r:
                continue
            up = sum(1 for x in r if x[2] > 0) / float(len(r))
            lens = sorted(x[1] - x[0] for x in r)
            rec["barriers"].append({
                "bps": b, "races": len(r), "share_up": up,
                "median_days": lens[len(lens) // 2],
                "needed_for_observed": needed(max(up, 1 - up))})
        out["symbols"][sym] = rec
    return out


def render(d):
    L = ["generated by resolvable.py — do not edit by hand",
         "daily candles from %s, non-overlapping races only" % d["start"], ""]
    L.append("sample size needed to separate a given rate from a coin flip")
    L.append("(two-sided, alpha 0.05, power 0.80)")
    for a in d["alternatives"]:
        L.append("   %.2f vs 0.50 needs %6d independent races"
                 % (a, d["needed"]["%.2f" % a]))
    for sym, r in d["symbols"].items():
        L.append("")
        L.append("%s   %d daily candles   %.1f years of history"
                 % (sym, r["candles"], r["years"]))
        L.append("  barrier   races   share up   median days   needed for that rate")
        for b in r["barriers"]:
            short = b["races"] < b["needed_for_observed"]
            L.append("  %5d bps %7d %10.2f %13d %16d   %s"
                     % (b["bps"], b["races"], b["share_up"], b["median_days"],
                        b["needed_for_observed"],
                        ("SHORT by %.1fx" % (b["needed_for_observed"] / float(b["races"])))
                        if short else "enough"))
    return "\n".join(L)


def main():
    if "--fetch" in sys.argv:
        d = compute()
        io.open(RUN, "w", encoding="utf-8").write(json.dumps(d, indent=1))
        print("wrote %s" % RUN)
    d = json.load(io.open(RUN, encoding="utf-8"))
    block = render(d)
    if os.path.exists(DOC):
        src = io.open(DOC, encoding="utf-8").read()
        a, b = "<!-- RESOLVABLE:BEGIN -->", "<!-- RESOLVABLE:END -->"
        if a in src and b in src:
            src = src[:src.index(a) + len(a)] + "\n```\n" + block + "\n```\n" + src[src.index(b):]
            io.open(DOC, "w", encoding="utf-8").write(src)
            print("updated %s" % DOC)
            return 0
    print(block)
    return 0


if __name__ == "__main__":
    sys.exit(main())
